project_id = "sqbqutpuiqwwclyxjeem"

[functions.mongodb-api]
verify_jwt = false

[functions.sms-api]
verify_jwt = false

[functions.fivesim-proxy]
verify_jwt = false

[functions.service-code-lookup]
verify_jwt = false

[functions.fivesim-stock]
verify_jwt = false

[functions.verify-upi]
verify_jwt = false

[functions.smsbower-proxy]
verify_jwt = false

[functions.process-cancellations]
verify_jwt = false

[functions.paytm-verify]
verify_jwt = false

[functions.paytm-initiate]
verify_jwt = false

[functions.cryptomus-initiate]
verify_jwt = false

[functions.cryptomus-webhook]
verify_jwt = false
